// Subset-fit parity twin, client half (issue #315 F2a).
//
// The committed expectation (`__fixtures__/subsetFitParity.expected.json`)
// is GENERATED by this implementation — the client fit owns the subset
// semantics — and the server port (rl_trajectories/subset_fit.py, pytest
// tests/test_subset_fit.py) must reproduce it structurally. This half
// guards the source of truth itself: if buildHdbscanHierarchy changes
// behavior, this test fails instead of letting the fixture drift silently.
//
// Regenerate after an INTENTIONAL semantics change with:
//   REGEN_FIT_FIXTURE=1 npx jest src/dataPreprocessing/hdbscanHierarchy.parity.test.ts
// then re-run the pytest twin.

import fs from "fs";
import path from "path";
import { buildHdbscanHierarchy } from "./hdbscanHierarchy";

const fixtureDir = path.join(__dirname, "__fixtures__");
const pointsPath = path.join(fixtureDir, "subsetFitParity.points.json");
const expectedPath = path.join(fixtureDir, "subsetFitParity.expected.json");

describe("subset-fit parity fixture (issue #315 F2a)", () => {
  const cases = JSON.parse(fs.readFileSync(pointsPath, "utf8")) as Record<
    string,
    Array<[number, number]>
  >;
  const built: Record<string, unknown> = {};
  for (const [name, pts] of Object.entries(cases)) {
    built[name] = buildHdbscanHierarchy(pts.map(([x, y]) => ({ x, y })));
  }

  if (process.env.REGEN_FIT_FIXTURE) {
    it("regenerates the expected fixture", () => {
      fs.writeFileSync(expectedPath, JSON.stringify(built));
      expect(fs.existsSync(expectedPath)).toBe(true);
    });
    return;
  }

  it("client fit reproduces the committed expectation", () => {
    const expected = JSON.parse(fs.readFileSync(expectedPath, "utf8"));
    // Round-trip through JSON so float serialization matches the fixture's
    // (lossless for float64) and undefined-valued fields drop out.
    expect(JSON.parse(JSON.stringify(built))).toEqual(expected);
  });
});
