/**
 * Integration parity: an existing dataset in the simple CSV format
 * (combination_example_2.csv) run through the in-app pipeline must produce
 * the same structural artifacts as the offline-preprocessed JSON equivalent
 * (combination-example-2_knng_splines_stability.json.gz, generated by
 * preprocess_dataset_generate_knng.py) — same points, same trajectory
 * partition, same spline segment/midpoint counts, and clustering
 * hierarchies over the same leaves. Numeric hierarchy internals differ
 * (different HDBSCAN implementations), which is fine: the runtime only
 * needs the tree contract (leafIndex + bbox per leaf).
 */
import * as fs from "fs";
import * as path from "path";
import * as zlib from "zlib";
import Papa from "papaparse";
import type { ClusterTreeNode } from "../clustering/ExtendedHDBSCAN";
import {
  buildSimpleDatasetObject,
  inferSimpleColumnMapping,
  type SimpleColumnMapping,
} from "./simpleDataset";

// site/ = the Pages publish dir; its tracked data fixtures exist nowhere else.
const DATA_DIR = path.resolve(process.cwd(), "site/data");

const readCsvRows = (): { rows: Record<string, unknown>[]; headers: string[] } => {
  const text = fs.readFileSync(path.join(DATA_DIR, "combination_example_2.csv"), "utf8");
  const parsed = Papa.parse<Record<string, unknown>>(text, {
    header: true,
    skipEmptyLines: true,
  });
  return { rows: parsed.data, headers: parsed.meta.fields ?? [] };
};

interface ReferenceJson {
  data: Array<{ line: unknown; x: number; y: number }>;
  knnGraph: number[][];
  hdbscan: { hierarchyTree: ClusterTreeNode };
  midpointHdbscan: { hierarchyTree: ClusterTreeNode };
}

const readJsonEquivalent = (): ReferenceJson => {
  const gz = fs.readFileSync(
    path.join(DATA_DIR, "combination-example-2_knng_splines_stability.json.gz")
  );
  return JSON.parse(zlib.gunzipSync(gz).toString("utf8")) as ReferenceJson;
};

const countLeaves = (tree: ClusterTreeNode): number => {
  let leaves = 0;
  const stack: ClusterTreeNode[] = [tree];
  while (stack.length) {
    const node = stack.pop()!;
    if (!node.leftChild && !node.rightChild) leaves++;
    if (node.leftChild) stack.push(node.leftChild);
    if (node.rightChild) stack.push(node.rightChild);
  }
  return leaves;
};

describe("simple-format pipeline parity with the offline-preprocessed JSON", () => {
  const { rows, headers } = readCsvRows();
  const inferred = inferSimpleColumnMapping(headers);
  const obj = buildSimpleDatasetObject(rows, inferred as SimpleColumnMapping, {
    datasetType: "default",
  });
  const reference = readJsonEquivalent();

  it("infers the column roles of the offline pipeline", () => {
    expect(inferred.x).toBe("x");
    expect(inferred.y).toBe("y");
    expect(inferred.trajectory).toBe("line");
    expect(inferred.order).toBe("step");
  });

  it("reproduces the point set and trajectory partition", () => {
    expect(obj.data).toHaveLength(reference.data.length);
    expect(obj.droppedRowCount).toBe(0);

    const partition = (points: Array<{ line: unknown; x: unknown }>) => {
      const byLine = new Map<string, number>();
      for (const p of points) {
        const key = String(p.line);
        byLine.set(key, (byLine.get(key) ?? 0) + 1);
      }
      return Array.from(byLine.values()).sort((a, b) => a - b);
    };
    // Line ids are re-densified in-app; the partition sizes must match.
    expect(partition(obj.data)).toEqual(partition(reference.data));

    // Same coordinates in the same per-line order.
    const coordKey = (points: Array<{ x: number; y: number }>) =>
      points.map((p) => `${p.x},${p.y}`).sort();
    expect(coordKey(obj.data)).toEqual(coordKey(reference.data));
  });

  it("produces spline geometry for every trajectory edge and sklearn-shaped kNN rows", () => {
    // This reference file predates the offline geometry outputs, so derive
    // the expected counts from the trajectory partition: one midpoint and
    // 20 spline segments per consecutive-point edge.
    const byLine = new Map<string, number>();
    for (const p of reference.data) {
      const key = String(p.line);
      byLine.set(key, (byLine.get(key) ?? 0) + 1);
    }
    const edgeCount = Array.from(byLine.values()).reduce((acc, n) => acc + Math.max(0, n - 1), 0);
    expect(obj.segments).toHaveLength(edgeCount * 20);
    expect(obj.trajectoryMidpoints).toHaveLength(edgeCount);

    // kNN: same row count and row length (the reference was produced with
    // k=5) and self-inclusive rows, like sklearn's kneighbors.
    expect(obj.knnGraph).toHaveLength(reference.knnGraph.length);
    obj.knnGraph.forEach((row, i) => {
      expect(row).toHaveLength(reference.knnGraph[i].length);
      expect(row).toContain(i);
    });
  });

  it("produces both hierarchies over the same leaves as the offline pipeline", () => {
    expect(obj.hdbscan).toBeDefined();
    expect(countLeaves(obj.hdbscan!.hierarchyTree)).toBe(
      countLeaves(reference.hdbscan.hierarchyTree)
    );
    expect(obj.midpointHdbscan).toBeDefined();
    expect(countLeaves(obj.midpointHdbscan!.hierarchyTree)).toBe(
      countLeaves(reference.midpointHdbscan.hierarchyTree)
    );
  });
});
